- .gitignore
- package-lock.json
- package.json
- src/app.ts
- tsconfig.json
- 백엔드 TypeScript + Express 프로젝트 초기 구조 세팅
- 기본 .gitignore 적용
---
- Express + TypeScript 프로젝트 기본 구조 구성
- `nodemon`, `concurrently`, `cors`, `figlet`, `express` 등 의존성 설치
- 기본 서버 실행 구조 작성 (app.ts)
- 포트 9000번 사용 설정
- .gitignore 작성 및 적용
- node_modules, dist, .env, IDE 설정, OS 숨김파일 등 
---
- `src/app.ts`
- `.gitignore`
-  `tsconfig.json`
-  `package.json`
- `package-lock.json`
---
- 라우터 경로는 추후 작성 예정
- 추가 API는 다음 브랜치에서 진행 예정
> 초기 프로젝트 세팅

- prisma/migrations/20250709063250_init/migration.sql
- prisma/schema.prisma
- `Client`, `Mover` 모델 수정
- `User` 모델 삭제, `Region` 모델 생성
---
- phone @unique 속성 추가
- livingArea(사는 지역) 필드 추가  
- nickName, career, introduction, description 옵셔널로 변경
- phone @unique 속성 추가
- serviceArea(서비스지역) 필드 추가
---
- `/schema.prisma`
---
---
- `git pull` 하시고 `npx prisma generate` 하시면 됩니다.
안되면 `npx prisma migrate reset`하고 해주세요.
> feat: 스키마 수정

- http/review.http
- package-lock.json
- package.json
- src/app.ts
- src/controllers/estimate.controller.ts
- src/controllers/review.controller.ts
- src/dtos/review.dto.ts
- src/middlewares/fakeAuth.ts
- src/repositories/estimate.repository.ts
- src/repositories/review.repository.ts
- src/routers/estimate.router.ts
- src/routers/review.router.ts
- src/services/estimate.service.ts
- src/services/review.service.ts
- src/types/express.d.ts
- src/types/index.ts
- src/types/review.d.ts
- tsconfig.json
- 리뷰 API 제작
- zod 추가
---
---
- `src/app.ts`
- `src/types/express.d.ts`
- `tsconfig.json`
- `src/types/index.ts`
---
- `src/controllers/estimate.controller.ts`
- `src/repositories/estimate.repository.ts`
- `src/repositories/review.repository.ts`
- `src/routers/estimate.router.ts`
- `src/routers/review.router.ts`
- `src/services/estimate.service.ts`
- `src/services/review.service.ts`
- `src/dtos/review.dto.ts`
- `src/middlewares/fakeAuth.ts`
- `src/types/review.d.ts`
---
- auth.userId 관련해서 오류가 날 수도 있습니다 오류가 날 경우 확인후 다시 pr하겠습니다
> feat: 리뷰 API 제작 및 zod 추가

- src/app.ts
- src/constants/ErrorMessage.ts
- src/middlewares/auth.middleware.ts
- src/utils/token.util.ts
- verifiedAccessToken 미들웨어 생성
- `auth.middleaware.ts` 파일만 보시면 됩니다
---
---
---
- `src/middlewares/auth.middleware.ts`
---
- 추후 수정 가능성 있습니다
> feat: verifiedAccessToken 미들웨어 생성

- http/auth.http
- src/constants/ErrorMessage.ts
- src/controllers/authClient.controller.ts
- src/dtos/auth/authClient.dto.ts
- src/repositories/authClient.repository.ts
- src/routers/auth.router.ts
- src/services/authClient.service.ts
- src/types/authClient.types.ts
- src/types/index.ts
- src/utils/authClient.utils.ts
- client 회원가입/로그인 api 제작 (POST)
---
---
- `http/auth.http`
- `src/constants/ErrorMessage.ts` (있는 파일 그대로 썼는데 파일명이랑 변수명 컨벤션이 안 맞는 것 같습니다.)
- `src/routers/auth.router.ts`
- `src/types/index.ts`
---
- `src/controllers/authClient.controller.ts`
- `src/dtos/auth/authClient.dto.ts`
- `src/repositories/authClient.repository.ts`
- `src/types/authClient.types.ts`
- `src/utils/authClient.utils.ts`
---
- 겹치는 데이터(함수 등)는 수경 님과 이야기해서 합칠 예정입니다.
> feat: 회원 회원가입/로그인 api 완성

- prisma/migrations/20250714015840_add_designated_request_model/migration.sql
- migration 파일을 빼먹고 올려서 추가로 올립니다.. 
---
- x
---
- x
---
- `migration.sql`
---
- x
> feat: migration 파일 추가

- http/auth.http
- src/constants/ErrorMessage.ts
- src/controllers/auth.controller.ts
- src/controllers/authClient.controller.ts
- src/controllers/profileClient.controller.ts
- src/dtos/authClient.dto.ts
- src/dtos/profileClient.dto.ts
- src/repositories/authClient.repository.ts
- src/repositories/profileClient.repository.ts
- src/routers/auth.router.ts
- src/services/authClient.service.ts
- src/services/profileClient.service.ts
- src/types/authClient.types.ts
- src/utils/auth.util.ts
- src/utils/authClient.util.ts
- 배포 사이트에서 회원가입 안 되는 것 수정
- 프로필 만드는 중(에 돌아가서 코드가 섞여 있음)
---
---
- `src/constants/ErrorMessage.ts`
- `src/controllers/auth.controller.ts`
- `src/controllers/authClient.controller.ts`
- `src/repositories/authClient.repository.ts`
- `src/routers/auth.router.ts`
- `src/types/authClient.types.ts`
- `src/utils/auth.util.ts`
---
- `src/dtos/profileClient.dto.ts`
- `src/repositories/profileClient.repository.ts`
- `src/services/profileClient.service.ts`
---
-
> fix: 배포 사이트에서 회원가입 안 되는 것 수정

- http/auth.http
- src/controllers/accountMover.controller.ts
- src/controllers/auth.controller.ts
- src/repositories/profileMover.respository.ts
- src/services/accountMover.service.ts
- src/types/account.types.ts
- 기사님 자동로그아웃 버그 해결
---
---
- `src/controllers/auth.controller.ts`
- `src/repositories/profileMover.repository.ts`
---
---
> fix: 기사님 자동로그아웃 버그 해결

- src/routers/estimate.router.ts
- src/services/estimate.service.ts
- 대기 중인 견적 기사 상세 정보 추가 구현
---
---
- `/src/services/estimate.service.ts`
- `/src/routers/estimate.router.ts`
---
X
---
- 대기 중인 견적 조회 api 주소가 잘 못 되어 수정 했습니다.
> feat: 대기 중인 견적 기사 상세 정보 추가 구현

- http/auth.http
- src/controllers/auth.controller.ts
- src/repositories/authClient.repository.ts
- src/repositories/authMover.repository.ts
- src/repositories/profileClient.repository.ts
- src/utils/auth.util.ts
- 로그인 시 일반 회원 livingArea 받게 설정, 사용자 정보에서 비밀번호 감춤
---
---
- `src/repositories/authClient.repository.ts`
- `src/repositories/authClient.repository.ts`
- `src/repositories/profileClient.repository.ts`
- `src/utils/auth.util.ts`
---
- x
---
- x
> fix: 로그인 시 일반 회원 livingArea 받게 설정, 사용자 정보에서 비밀번호 감춤

- src/controllers/estimate.controller.ts
- src/routers/estimate.router.ts
- src/services/estimate.service.ts
- 견적 컨트롤러 및 서비스 로직 수정
- API 응답 포맷 및 라우팅 흐름 개선
---
- `estimate.controller.ts`: 불필요한 예외 처리 제거 및 응답 메시지 일관화
- `estimate.service.ts`: estimate 상태별 조회 로직 리팩토링 및 유효성 검사 추가
- `estimate.router.ts`: API 라우팅 구조 정리 및 가독성을 위한 주석 보강
---
- `src/controllers/estimate.controller.ts`
- `src/routers/estimate.router.ts`
- `src/services/estimate.service.ts`
---
- 없음
---
- 프론트엔드에서 이 API를 사용하는 경우, 응답 데이터 구조가 일부 변경되었을 수 있으니 확인 필요
- 추후 `/estimates/:id` 상세 조회 API에도 동일한 응답 포맷 적용 예정
> feat: 견적 API 로직 업데이트 및 컨트롤러/라우터/서비스 통합 수정 및 작성

- prisma/migrations/20250725054709_add_nullable_field/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- 스키마 수정, 시딩 코드 수정
---
---
- `schema.prisma`
- `seed.ts`
---
- x
---
- `npx prisma generate` 한번씩 부탁드립니다.
> feat: 스키마 수정, 시딩 코드 수정

- src/controllers/authClient.controller.ts
- src/repositories/authClient.repository.ts
- src/repositories/authMover.repository.ts
- src/repositories/mover.repository.ts
- src/services/authClient.service.ts
- src/services/authMover.service.ts
- src/services/estimate.service.ts
- src/services/profileMover.service.ts
- src/services/request.service.ts
- src/types/auth.types.ts
- 소셜 로그인 작업 중 스키마 수정으로 발생한 문제 해결
---
---
- 오류 발생한 파일 전체
---
- x
---
- x
> fix: 스키마에서 name 등 nullable 처리 시 발생 문제 해결

- src/repositories/favorite.repository.ts
-  isLiked 추가
---
---
- `src/repositories/favorite.repository.ts`
> refactor: isLiked 추가

- src/controllers/review.controller.ts
> fix: 리뷰 삭제 오류 수정

- src/constants/ErrorMessage.ts
- 프로필 오류 관련 에러 해결
---
---
- `ErrorMessage.ts`
---
x
---
x
> fix: 프로필 오류 관련 에러 해결

- src/controllers/accountMover.controller.ts
- src/controllers/authMover.controller.ts
- src/controllers/profileMover.controller.ts
- src/dtos/accountMover.dto.ts
- src/middlewares/auth.middleware.ts
- src/middlewares/profile.middleware.ts
- src/repositories/profileMover.respository.ts
- src/routers/account.router.ts
- src/routers/auth.router.ts
- src/routers/profile.router.ts
- src/services/accountMover.service.ts
- src/utils/auth.util.ts
- 기본 정보 수정 관련 로직 수정 & 리펙터 
---
---
- `src/controllers/authMover.controller.ts`
- `src/controllers/profileMover.controller.ts`
- `src/dtos/accountMover.dto.ts`
- `src/middlewares/auth.middleware.ts`
- `src/repositories/profileMover.respository.ts`
- `src/routers/account.router.ts`
- `src/routers/auth.router.ts`
- `src/routers/profile.router.ts`
- `src/services/accountMover.service.ts`
- `src/utils/auth.util.ts`
---
- `src/middlewares/profile.middleware.ts`
---
> fix:기사님 기본정보 수정 관련 에러 수정

- src/configs/passport.config.ts
- src/services/authMover.service.ts
- 파일명 PR 반영이 안 돼서 다시 올림
---
---
- x
---
- x
---
- x
> chore: 파일명 변경 사항 반영 위해 PR 재등록

- http/mover.http
- src/controllers/mover.controller.ts
- src/controllers/request.controller.ts
- src/repositories/mover.repository.ts
- src/repositories/request.repository.ts
- src/routers/mover.router.ts
- src/routers/request.router.ts
- src/services/mover.service.ts
- src/services/request.service.ts
- api 경로오류 수정
---
---
- `/mover.router, controller, service, repository`
- `/request.router, controller, service, repository`
---
---
> fix: 지정견적 요청 api 경로오류 수정

- package.json
- src/routers/request.router.ts
- 스키마 수정 시 빌드 오류 발생 관련 스크립트 추가
---
---
---
- x
---
- x
> fix: 빌드 오류 수정

- src/configs/passport.config.ts
- src/controllers/auth.controller.ts
- src/middlewares/passport/googleStrategy.ts
- src/repositories/authMover.repository.ts
- src/services/authClient.service.ts
- src/services/authMover.service.ts
- 소셜 로그인 - Client와 Mover 코드 통합 완료
---
---
- `src/controllers/auth.controller.ts`
- `src/middlewares/passport/googleStrategy.ts`
- `src/repositories/authMover.repository.ts`
---
- x
---
- 배포 사이트에서 게이트웨이 오류가 나고 있어서 확인해야 합니다.
- 로컬에서는 완벽하게 됩니다. (**구글만**)
- 17:30에 다같이 시험하려고 일단 올린 것이고, 오류 메시지 등 수정은 저녁에 최종 PR 올립니다.
> refactor: 소셜 로그인 - Client와 Mover 코드 통합 완료

- package-lock.json
- src/controllers/review.controller.ts
- src/routers/review.router.ts
- 기사님 리뷰 통합
---
---
- `src/routers/review.router.ts`
---
---
> refactor: 기사님 리뷰 통합

- package-lock.json
- package.json
- src/app.ts
- `npm run start` 시 import 경로 인식 못하는 에러 해결
---
---
- `package.json`, `package-lock.json`
- `app.ts`
---
- x
---
- x
> fix: 경로 alias 오류 수정

- src/controllers/request.controller.ts
- src/repositories/request.repository.ts
- 받은 요청 컨트롤러 및 레포지토리 로직 구조 개선  
---
---
- `src/controllers/request.controller.ts`  
- `src/repositories/request.repository.ts`  
---
- 해당 없음  
---
- 프론트 필터 UI 구조와 맞춰 로직 리팩토링됨
> refactor: 받은 요청 컨트롤러 및 레포지토리 로직 구조 개선

- src/controllers/review.controller.ts
- src/repositories/mover.repository.ts
- src/routers/review.router.ts
- src/types/mover.type.ts
- 지정견적 칩 연결
- review router수정
---
---
- `src/repositories/mover.repository.ts`
- `src/routers/review.router.ts`
- `src/types/mover.type.ts`
---
---
> feat: 지정견적 칩

- src/services/estimate.service.ts
- 받은 견적 조회 수정
---
---
- `src/services/estimate.service.ts`
---
---
> fix: 받은 견적 조회 수정

- package.json
- github actions 배포 실패 오류 수정
---
---
---
- x
---
- x
> fix: 테스트 오류 수정

- src/controllers/authClient.controller.ts
- src/services/authClient.service.ts
- PR 반영하면서 구현하다 중단한 기능 쪽에서 타입이 지워졌는데 터미널창에 오류가 안 나서 그대로 올렸다가 배포 오류가 발생했고, 해당 오류 수정했습니다.
---
---
- `src/controllers/authClient.controller.ts`
---
- x
---
- x
> fix: 팀원 PR을 반영하면서 생긴 배포 오류 수정(타입 지워진 것 반영)

- src/repositories/favorite.repository.test.ts
- src/repositories/review.repository.test.ts
- src/services/favorite.service.test.ts
- src/services/favorite.service.ts
- src/services/review.service.test.ts
- 유닛 테스트코드 작성
---
---
- `src/services/favorite.service.ts`
---
- `src/repositories/favorite.repository.test.ts`
- `src/repositories/review.repository.test.ts`
- `src/services/review.service.test.ts`
> feat: review, favorite 유닛 테스트코드 작성

- .github/workflows/deploy.yml
- package.json
- 기존 배포 명령어 `git pull` 방식에서 scp 방식으로 수정
---
- scp 방식 적용
- 스크립트 `prisma generate` 명령어 제거
---
- `deploy.yml`
---
- x
---
- x
> fix: 워크플로우 수정

- src/dtos/auth.dto.ts
- src/middlewares/auth.middleware.ts
- 일반유저/기사님 로컬 인증 시 회원 탈퇴 안되는 에러 수정
---
---
- `src/dtos/auth.dtos.ts`
- `src/middlewares/auth.middleware.ts`
---
---
> fix: 일반유저/기사님 로컬 인증 시 회원 탈퇴 안되는 에러 수정

- .github/workflows/deploy.yml
- src/routers/request.router.ts
- src/swagger.yaml
- 받은 요청 목록 라우터 revert
---
---
- `request.router.ts`
- `deploy.yml`
- `swagger.yaml`
---
- x
---
- x
> fix: 받은 요청 목록 라우터 revert

- src/controllers/auth.controller.ts
- src/middlewares/auth.middleware.ts
- src/services/auth.service.ts
- src/services/authClient.service.ts
- src/utils/token.util.ts
- 일반 ↔ 소셜 중복 이메일 오류 수정 외
---
---
- `src/middlewares/auth.middleware.ts`
---
- x
---
- x
> fix: 일반 ↔ 소셜 중복 이메일 오류 수정 외

- src/middlewares/cache.middleware.ts
- src/routers/account.router.ts
- src/routers/auth.router.ts
- src/routers/estimate.router.ts
- src/routers/favorite.router.ts
- src/routers/image.router.ts
- src/routers/info.router.ts
- src/routers/mover.router.ts
- src/routers/notification.router.ts
- src/routers/profile.router.ts
- src/routers/request.router.ts
- src/routers/review.router.ts
- src/routers/translation.router.ts
- redis 오류 수정 완료
---
---
- `src/middlewares/cache.middleware.ts`
- router 폴더 안의 전체 파일
---
- x
---
- x
> fix: redis 오류 수정 완료

- src/routers/account.router.ts
- src/routers/auth.router.ts
- src/routers/estimate.router.ts
- src/routers/favorite.router.ts
- src/routers/image.router.ts
- src/routers/info.router.ts
- src/routers/mover.router.ts
- src/routers/notification.router.ts
- src/routers/profile.router.ts
- src/routers/request.router.ts
- src/routers/review.router.ts
- src/routers/translation.router.ts
- redis 적용 코드 전체 제거
---
---
- 전체 router 파일
---
- x
---
- x
> chore: redis 적용 코드 전체 제거

- prisma/migrations/20250812064850_add_community/migration.sql
- prisma/schema.prisma
- src/app.ts
- src/controllers/community.controller.ts
- src/repositories/Community.repository.ts
- src/routers/community.router.ts
- src/services/community.service.ts
- src/types/Community.type.ts
- 커뮤니티 기능 구현
---
---
- `prisma/schema.prisma`
- `prisma/migrations/20250812064850_add_community/migration.sql`
- `src/app.ts`
---
- `src/routers/community.router.ts`
- `src/controllers/community.controller.ts`
- `src/services/community.service.ts`
- `src/repositories/Community.repository.ts`
- `src/types/Community.type.ts`
---
> Feat: 커뮤니티 기능 구현

- .github/workflows/deploy.yml
- 깃헙 액션 스크립트 prisma migrate 명령어 추가
---
---
- `deploy.yml`
---
- x
---
- x
> fix: 깃헙 액션 스크립트 prisma migrate 명령어 추가

- package.json
- src/integration-test/authClient.test.ts
- src/integration-test/authMover.test.ts
- src/integration-test/favorite.test.ts
- src/integration-test/index.test.ts
- src/integration-test/review.test.ts
- 통합테스트가 순서대로 진행되도록 코드 수정
---
---
- `src/integration-test/authClient.test.ts`
- `src/integration-test/authMover.test.ts`
- `src/integration-test/favorite.test.ts`
- `src/integration-test/review.test.ts`
---
- package.json 수정사항 확인해주세요
> refactor: index.test.ts에서 통합테스트가 순서대로 진행되도록 코드 수정

- src/controllers/review.controller.ts
- src/repositories/review.repository.ts
- src/services/review.service.test.ts
- src/services/review.service.ts
- src/swagger.yaml
- 기본 배포용 구조 세팅
---
---
- `src/repositories/review.repository.ts`
- `src/services/review.service.ts`
- `src/swagger.yaml`
> feat: 리뷰 작성 및 수정 이미지 추가

- src/controllers/favorite.controller.test.ts
- src/controllers/review.controller.test.ts
- src/controllers/translation.controller.test.ts
- src/integration-test/index.test.ts
- src/integration-test/translation.test.ts
- src/middlewares/translation.middleware.test.ts
- src/services/translation.service.test.ts
- 테스트 코드 작성
---
---
- `src/controllers/favorite.controller.test.ts`
- `src/controllers/review.controller.test.ts`
- `src/controllers/translation.controller.test.ts`
- `src/services/translation.service.test.ts`
- `src/middlewares/translation.middleware.test.ts`
- `src/integration-test/translation.test.ts`
> feat: translation 테스트 코드 작성

- src/controllers/estimate.controller.ts
- src/dtos/estimate.dto.ts
- src/repositories/Community.repository.ts
- 견적 관련 DTO 유효성 검사 추가
- Community Repository에서 `name` → `nickName` 필드 수정
---
---
- `src/controllers/estimate.controller.ts`
- `src/repositories/Community.repository.ts`
---
- `src/dtos/estimate.dto.ts`
---
- 닉네임 필드 불일치 문제 해결로 리스트/디테일 API 응답 일관성 확보
> feat: 견적 DTO 유효성 검사 추가 및 Community repository 닉네임 필드 수정

- src/controllers/community.controller.ts
- src/repositories/community.repository.ts
- src/routers/community.router.ts
- src/services/community.service.ts
- 커뮤니티 게시글, 댓글 수정 기능 추가
---
---
- `src/controllers/community.controller.ts`
- `src/repositories/community.repository.ts`
- `src/routers/community.router.ts`
- `src/services/community.service.ts`
---
- x
---
- x
> feat: 커뮤니티 게시글, 댓글 수정 기능 추가

- src/services/translation.service.ts
- ko 번역 추가
---
---
- `src/services/translation.service.ts`
> fix: ko 번역 추가
